version: "3"
services:
  admin:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: always
    networks:
      - voices-dev
    volumes:
      - .:/app

networks:
  voices-dev:
    external: true
